### ISSUE TITLE
Need to fix elements controller

### ISSUE THREAD

**Issue by Kryhowsky** [PRO-E-montazysta/PRO#19]
Two wrongly 'pathed' GET methods in elements controller.
/elements/{id} & /elements/{code}

> java.lang.IllegalStateException: Ambiguous handler methods mapped for '/api/v1/elements/1':

**Comment by kurylek** [comment]
I did same thing in Tools. Will fix it soon.

**Comment by kurylek** [comment]
Fixed in #20 - waiting for review and merge. Closing issuse.
